### ISSUE TITLE
old version request

### ISSUE THREAD

**Issue by nevo33** [up209d/ResourcesSaverExt#58] opened 2022-09-22 06:12 UTC
Hello, thanks for all your hard work. But for me the new update has been a complete nightmare. the files are downloading incomplete, can you please republish the previous version for me.

**Comment by up209d** [comment] 2022-09-23 00:18
> Hello, thanks for all your hard work. But for me the new update has been a complete nightmare. the files are downloading incomplete, can you please republish the previous version for me.

Can you describe your issue in more detail, please?

**Comment by kilik128** [comment] 2022-09-23 15:01
same new version stop on Compressed  Processed: true
and nothing happen 
help is welcomme

**Comment by up209d** [comment] 2022-09-23 18:48
> same new version stop on Compressed  Processed: true
> 
> and nothing happen 
> 
> help is welcomme 

Any specific link that the extension has issue with? I need to be able to replicate the problem in order to fix it.

**Comment by mitakomeow** [comment] 2022-09-24 04:33
hi,  please roll back to old version.

**Comment by mitakomeow** [comment] 2022-09-24 04:45
[attack.zip](https://github.com/up209d/ResourcesSaverExt/files/9637954/attack.zip)

attach file is attack.html and only get
![image](https://user-images.githubusercontent.com/45625306/192080376-4f45cf98-a31e-4d3f-9c55-a74c9c6d3ad1.png)

**Comment by up209d** [comment] 2022-09-24 04:47
> [attack.zip](https://github.com/up209d/ResourcesSaverExt/files/9637954/attack.zip)
> 
> 
> 
> this version get this content 
> 
> ![image](https://user-images.githubusercontent.com/45625306/192080376-4f45cf98-a31e-4d3f-9c55-a74c9c6d3ad1.png)
> 
> 
> 
> the old version get the correct content is 
> 
> ![image](https://user-images.githubusercontent.com/45625306/192080410-d5b6917e-417f-42a5-80e5-736d57e9311b.png)
> 
> 

fixed in 2.0.2, publishing it to webstore atm

**Comment by up209d** [comment] 2022-09-24 15:32
<img src="https://github.com/up209d/ResourcesSaverExt/blob/master/screenshot-switch-version.png?raw=true" width="300" />

You will be able to switch back to old version by `2.0.3`. However, it would take a week for this version to be available on Chrome Ext Store. By now, just use the local extension.

**Comment by nevo33** [comment] 2022-09-24 22:43
I'm sorry that I couldn't answer the answers you gave to the question due to the busy tempo. but the version 2.0.3 you have published is still downloading the missing file. but it's good that you added the feature of reverting to the old version and I am doing the complete download with the old version. thanks

**Comment by nevo33** [comment] 2022-09-24 22:50
![image](https://user-images.githubusercontent.com/114133436/192121250-ce206f2b-8c25-4264-845c-9a1913424ce6.png)

**Comment by up209d** [comment] 2022-09-25 01:58
> ![image](https://user-images.githubusercontent.com/114133436/192121250-ce206f2b-8c25-4264-845c-9a1913424ce6.png)
> 
> 

It depends, if the difference above is caused by XHR option. The old one gonna reload the page once you hit XHR option, the new one doesnt have that option because it is always on by default, you need to reload the page yourself when you open devtool panel in order for it to record xhr requests.

**Closed** 2022-11-18 05:46 UTC
